title: O conhecimento nÃ£o para
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "https://morvanabonin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Morvana Bonin # add your name
author-img: morvana-bonin.jpg # add your photo
about-author: Desenvolvedora de software, com foco em desenvolvimento backend. Sempre com fome de continuar aprendendo. # add description
social-twitter: morvanabonin # add your Twitter handle
social-facebook: # add your Facebook handle
social-gitlab: morvanabonin # add your Gitlab handle
social-github: morvanabonin # add your Github handle
social-linkedin: morvanabonin # add your Linkedin handle
social-email: morvanabonin@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
# - jemoji
  - gemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
